version: '3.8'

services:
  backend:
    build:
      context: ./后端模块
    ports:
      - "8080:8080"
    restart: "on-failure"
    depends_on:
      - db
      - minio
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: task_manager
      SERVER_PORT: 8080
      JWT_KEY: mysecret
      GOPROXY: https://goproxy.cn,direct
      GOSUMDB: off
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: taskmanager

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./前端模块/dist:/usr/share/nginx/html:ro
      - ./前端模块/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  mysql_data:
  minio_data:

